apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: bind-namespace-creator-admin
  annotations:
    policies.kyverno.io/title: Add RoleBinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: RoleBinding
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Automatically assigns the namespace creator as an admin within the namespace,
      unless the user is a cluster-admin.
spec:
  background: false
  rules:
    - name: generate-admin-binding
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - clusterRoles:
              - cluster-admin
      generate:
        synchronize: true
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: "{{request.userInfo.username}}-admin-binding"
        namespace: "{{request.object.metadata.name}}"
        data:
          metadata:
            annotations:
              kyverno.io/user: "{{request.userInfo.username}}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
            - kind: User
              name: "{{request.userInfo.username}}"
              apiGroup: rbac.authorization.k8s.io
